name: Build

on: workflow_dispatch

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: deploy
        uses: bourvill/action-astro@main
        with:
          bucket: 'marinel-blog'
          config: ${{ secrets.AWS_CONFIG }}
          cred: ${{ secrets.AWS_CRED }}